---
- hosts: all
  sudo: true
  tasks:
    - apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc id=ACCC4CF8
    - apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main' update_cache=no
    - apt_repository: repo='ppa:git-core/ppa' update_cache=no
    - apt: update_cache=yes
    - apt: name=git
    - apt: name=silversearcher-ag
    - apt: name=tree
    - apt: name=nodejs
    - apt: name=mercurial
    - include_vars: vars/secrets.yml
    - include: tasks/ruby.yml
    - include: tasks/emacs.yml
    - include: tasks/postgresql.yml
    - include: tasks/go.yml
    - include: tasks/tmux.yml
    - include: tasks/redis.yml
    - include: tasks/cachefilesd.yml
    - include: tasks/heroku.yml
  handlers:
    - name: restart postgres
      action: service name=postgresql state=restarted
  vars:
    - ruby_version: 2.2.2
