---
- name: download chruby
  get_url: url=https://github.com/postmodern/chruby/archive/v0.3.9.tar.gz dest=/tmp/chruby-v0.3.9.tar.gz sha256sum=7220a96e355b8a613929881c091ca85ec809153988d7d691299e0a16806b42fd
- name: unpack chruby
  unarchive: src=/tmp/chruby-v0.3.9.tar.gz dest=/tmp copy=no
- name: install chruby
  command: make install chdir=/tmp/chruby-0.3.9 creates=/usr/local/share/chruby
