---
- apt: name=lxc-docker
- name: install docker-compose
  get_url: dest=/usr/local/bin/docker-compose mode=0755 url=https://github.com/docker/compose/releases/download/1.3.2/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}
