---
- name: download go
  get_url: url=https://storage.googleapis.com/golang/go1.4.2.linux-amd64.tar.gz dest=/tmp/go1.4.2.linux-amd64.tar.gz sha256sum=141b8345932641483c2437bdbd65488a269282ac85f91170805c273f03dd223b
- name: install go
  unarchive: src=/tmp/go1.4.2.linux-amd64.tar.gz dest=/usr/local creates=/usr/local/go copy=no
- name: configure go env
  copy: src=files/go.sh dest=/etc/profile.d/go.sh owner=root group=root mode=0644
