---
- include: ruby-install.yml
- include: chruby.yml
- name: install ruby {{ ruby_version }}
  command: ruby-install --jobs=4 ruby {{ ruby_version }} -- --disable-install-doc creates=/opt/rubies/ruby-{{ ruby_version }}
- name: install global utility gems
  gem: name={{item}} executable=/opt/rubies/ruby-{{ ruby_version }}/bin/gem user_install=no
  with_items:
    - bundler
    - dotenv
    - zeus
