---
- include: ruby-install.yml
- include: chruby.yml
- name: install ruby {{ ruby_version }}
  command: ruby-install --jobs=4 ruby {{ ruby_version }} -- --disable-install-doc creates=/opt/rubies/ruby-{{ ruby_version }}
- gem: name=bundler executable=/opt/rubies/ruby-{{ ruby_version }}/bin/gem user_install=no
- gem: name=dotenv executable=/opt/rubies/ruby-{{ ruby_version }}/bin/gem user_install=no
- gem: name=zeus executable=/opt/rubies/ruby-{{ ruby_version }}/bin/gem user_install=no
