---
- name: download ruby-install
  get_url: url=https://github.com/postmodern/ruby-install/archive/v0.5.0.tar.gz dest=/tmp/ruby-install-v0.5.0.tar.gz sha256sum=aa4448c2c356510cc7c2505961961a17bd3f3435842831e04c8516eb703afd19
- name: unpack ruby-install
  unarchive: src=/tmp/ruby-install-v0.5.0.tar.gz dest=/tmp copy=no
- name: install ruby-install
  command: make install chdir=/tmp/ruby-install-0.5.0 creates=/usr/local/bin/ruby-install
